language: python
python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"
  # PyPy versions
#  - "pypy3.5"

install:
  - pip install -r requirements-dev.txt
  - pip install .

script:
  - pytest --cov=zmei_generator/
after_success:
  - coveralls