language: python
python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"
  # PyPy versions
#  - "pypy3.5"

install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - pip install -r requirements-dev.txt
  - pip install .

before_script:
  - ./cc-test-reporter before-build

script:
  - pytest --cov=zmei_generator/

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
